### ISSUE TITLE
unable to transfer maintainership

### ISSUE THREAD

**Issue by chorny** [andk/pause#145] opened 2015-02-23 19:35 UTC
I tried to transfer maintainership for Tk::ToolBar, it is module registered in modulelist, so it is listed in "1. You are registered in modulelist ". After I press "Select" (for 1), nothing happens, I'm transferred to URL https://pause.perl.org/pause/authenquery

**Comment by karenetheridge** [comment] 2015-02-23 19:43
@andk can all 'm' entries in the permissions database be switched to 'f', to get past this issue?

(It is possible that some modules might end up with more than one 'f', but I don't think this will cause problems in the short term - it is similar to the current issue where some modules have 'm' entries but no 'f'.)

**Comment by briandfoy** [comment] 2015-03-02 17:43
I was trying to transfer primary maintainership of Math::FFT to Shlomi but couldn't do it. This is a Randy Kobes module which is now ADOPTME and is registered in the module list. When I go to the Change Permissions page, select Math::FFT in 1.) and then click Select, I'm taken back to the main PAUSE menu instead of the Edit Module Metadata page.

I've given Shlomi co-maintainer privileges so far, but the module should leave ADOPTME if someone is caring for it.

**Comment by andk** [comment] 2015-03-03 04:54
Yes, I think this is a duplicate of 141. I will not do bulk updates on the PAUSE database unless I'm absolutely sure I do not break anything. Currently I'm still coward on this, so you must be patient and let me change the database case-by-base. Both Tk::ToolBar and Math::FFT look to me OK: they have the 'delete' flag on mods table, so appear to me as 'module list' in the view pemissions page and as "2" in the change permissions page. @chorny and @bdfoy, please retry.

**Comment by briandfoy** [comment] 2015-03-03 13:45
I don't think you should do bulk updates either.

I might suggest that in the meantime, for the very few instances where this
is a problem, someone has a special tool to hit the database directly to
flip permissions.

**Comment by chorny** [comment] 2015-03-03 13:58
Transfer worked for Tk::ToolBar.
Now ASB has first-come rights and I have modulelist. I'm not sure if this is correct.

**Comment by chorny** [comment] 2015-10-29 16:50
JEFFOBER has similar problems with Reddit::Client::* - see https://rt.cpan.org/Ticket/Display.html?id=108093

**Comment by andk** [comment] 2015-10-30 07:40
>>>>> On Thu, 29 Oct 2015 09:50:59 -0700, Alexandr Ciornii <notifications@github.com> said:

  > JEFFOBER has similar problems with Reddit::Client::* - see https://rt.cpan.org/
  > Ticket/Display.html?id=108093

Thanks Alex,

"Made EARTHTONE primary maintainer of Reddit::Client."

Please let me know if something remains to be transferred.

-- 
andreas

**Comment by charsbar** [comment] 2019-04-27 12:57
This should already been fixed. Closing.

**Closed by charsbar** 2019-04-27 12:57 UTC
