### ISSUE TITLE
when all permissions dropped, transfer to ADOPTME?

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#169] opened 2015-05-03 22:46 UTC
As announced in http://www.xenoterracide.com/2015/05/abandoning-all-perl-modules.html, XENO dropped permissions on most of his modules today. He did not transfer them to ADOPTME.  This means that there are now modules out there that are still indexed in 02packages that have no corresponding entry in 06perms.

I am pondering whether this should be permitted? That is, if a module is still in the 02packages index, it should not be possible to drop all permissions entirely, but instead the permission should be required to be transferred to another user (ADOPTME or HANDOFF being the prime candidates).  Are there any negative consequences to there being no permissions registered for indexed modules?

**Comment by dagolden** [comment] 2015-05-03 23:22
Can someone upload and get first-come?

Perhaps "drop primary" should email PAUSE admins so someone can investigate?

In this case, it seems like ADOPTME is the right owner.

**Comment by karenetheridge** [comment] 2015-05-04 01:01
> Can someone upload and get first-come?

That would be my guess.

I've requested first-come on these modules from a PAUSE admin, so they can be maintained -- https://gist.github.com/karenetheridge/290ac9bcd8ce400eaf9e

**Comment by andk** [comment] 2015-05-04 03:56
>>>>> On Sun, 03 May 2015 18:01:20 -0700, Karen Etheridge <notifications@github.com> said:

  >     Can someone upload and get first-come?
  > That would be my guess.

Thas's also my recollection. Since having nothing in perms is just the
state before the first upload. I know of no other mechanism that would
kick in. And actually that's how it was designed. ADOPTME was invented
much later.

-- 
andreas

**Comment by rjbs** [comment] 2023-04-28 12:18
I've updated the name to reflect the apparent final intent here.

**Comment by rjbs** [comment] 2023-04-29 07:50
I bet this is documented in the operating model!  Andreas believe his intention was to make the change described.

**Comment by charsbar** [comment] 2023-04-30 11:08
https://github.com/andk/pause/blob/master/doc/operating-model.md?plain=1#L330-L335

> In the near future,
we plan to modify PAUSE so that
"giving up your first-come indexing permission"
will result in first-come being transferred to the special user **`ADOPTME`**
(described in §4.5.1 below),
if other people have admin or co-maint permissions.

**Comment by charsbar** [comment] 2023-04-30 11:31
I didn't remember what I did in 2019: https://github.com/andk/pause/commit/4cf17b0a799f242dd09091354fc8c362f421e23d

**Closed by charsbar** 2023-04-30 11:31 UTC
Labels: webui, feature-request, permissions
