### ISSUE TITLE
new feature: "delete upload immediately"

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#51] opened 2013-05-24 17:05 UTC
The three day delay for deletions is sometimes highly inconvenient - e.g. when dealing with an upload that was a mistake.  It would be very helpful to have an option to immediately delete an upload -- it could be limited to one that was uploaded in the last hour, to prevent FYIQ-type abuses.

That would also greatly reduce the amount of personal involvement andk needs to take in sorting out indexing problems. :)

**Comment by charsbar** [comment] 2019-04-28 14:25
This is a duplicate of #163. Closing.

**Closed by charsbar** 2019-04-28 14:25 UTC
